version: '3.8'

services:
  server:
    image: node
    command: node server.js
    networks:
      - net
    volumes:
      - ./node/server.js:/server.js
    deploy:
      replicas: 3

  gateway:
    depends_on:
      - server
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - net
    ports:
      - 8000:80

networks:
  net:
    driver: overlay
